"""Stub file for reflex_reactbits/base.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
import reflex as rx
from reflex.components.component import NoSSRComponent

SAFE_FN_NAME = "reactbitsSafe"
SAFE_FN_CODE = '\nconst reactbitsSafe = (value, depth = 0, seen = new WeakSet()) => {\n  if (value === undefined || value === null) return null;\n  const kind = typeof value;\n  if (kind === "function" || kind === "symbol") return undefined;\n  if (kind === "bigint") return Number(value);\n  if (kind === "number") return Number.isFinite(value) ? value : null;\n  if (kind !== "object") return value;\n  if (value.$$typeof) return undefined;\n  if (value.nativeEvent) return { type: value.type };\n  if (typeof Event !== "undefined" && value instanceof Event) return { type: value.type };\n  if (typeof Node !== "undefined" && value instanceof Node) return undefined;\n  if (typeof File !== "undefined" && value instanceof File)\n    return { name: value.name, size: value.size, type: value.type, lastModified: value.lastModified };\n  if (value instanceof Error) return { name: value.name, message: value.message };\n  if (value instanceof Date) return value.toISOString();\n  if (depth > 8 || seen.has(value)) return undefined;\n  seen.add(value);\n  if (Array.isArray(value) || (typeof FileList !== "undefined" && value instanceof FileList))\n    return Array.from(value, (item) => reactbitsSafe(item, depth + 1, seen) ?? null);\n  const out = {};\n  for (const [key, item] of Object.entries(value)) {\n    const safe = reactbitsSafe(item, depth + 1, seen);\n    if (safe !== undefined) out[key] = safe;\n  }\n  return out;\n};\n'

def safe(value: rx.Var) -> rx.Var: ...

class ReactBitsComponent(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ReactBitsComponent":
        """Copy the component source into the app (once) and create the component."""
        ...

    def add_custom_code(self) -> list[str]: ...
