"""Stub file for reflex_reactbits/micro.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.components.component import Component
from reflex_base.vars.base import Var
from .base import ReactBitsComponent

__all__ = [
    "BellToggle",
    "BranchedMenu",
    "CallChip",
    "CodeSlots",
    "CometDial",
    "DodgeField",
    "FolderFloat",
    "FuseButton",
    "GlideSelect",
    "HoldButton",
    "JellyRadio",
    "LatticeLoader",
    "PeekRating",
    "PromptBar",
    "PulseHeart",
    "RefineFrame",
    "RubberSegment",
    "ScrubField",
    "SlideCommit",
    "SlingButton",
    "SloshGauge",
    "SpringCheck",
    "SquishSwitch",
    "StatusMark",
    "SwipeRow",
    "SwipeToast",
    "ThoughtLine",
    "VoicePill",
    "WakeSlider",
    "WarmTooltip",
    "WarmTooltipGroup",
    "bell_toggle",
    "branched_menu",
    "call_chip",
    "code_slots",
    "comet_dial",
    "dodge_field",
    "folder_float",
    "fuse_button",
    "glide_select",
    "hold_button",
    "jelly_radio",
    "lattice_loader",
    "peek_rating",
    "prompt_bar",
    "pulse_heart",
    "refine_frame",
    "rubber_segment",
    "scrub_field",
    "slide_commit",
    "sling_button",
    "slosh_gauge",
    "spring_check",
    "squish_switch",
    "status_mark",
    "swipe_row",
    "swipe_toast",
    "thought_line",
    "voice_pill",
    "wake_slider",
    "warm_tooltip",
    "warm_tooltip_group",
]

class BellToggle(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        off_label: Var[str] | str | None = None,
        on_label: Var[str] | str | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        label: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        background: Var[str] | str | None = None,
        on_color: Var[str] | str | None = None,
        on_background: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        ring_amplitude: Var[float | int] | float | int | None = None,
        ring_passes: Var[float | int] | float | int | None = None,
        ring_decay: Var[float | int] | float | int | None = None,
        ring_duration: Var[float | int] | float | int | None = None,
        ring_pivot: Var[float | int] | float | int | None = None,
        crossfade_ms: Var[float | int] | float | int | None = None,
        reveal_bounce: Var[float | int] | float | int | None = None,
        count: Var[float | int] | float | int | None = None,
        badge: Var[bool] | bool | None = None,
        badge_color: Var[str] | str | None = None,
        badge_text_color: Var[str] | str | None = None,
        waves: Var[bool] | bool | None = None,
        clapper: Var[bool] | bool | None = None,
        pressed: Var[bool] | bool | None = None,
        default_pressed: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "BellToggle":
        """Copy the component source into the app (once) and create the component."""
        ...

class BranchedMenu(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[Any]] | list[Any] | None = None,
        default_open: Var[float | int | list[float | int]]
        | float
        | int
        | list[float | int]
        | None = None,
        default_active: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        accent_color: Var[str] | str | None = None,
        line_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        row_height: Var[float | int] | float | int | None = None,
        indent: Var[float | int] | float | int | None = None,
        trunk: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        line_width: Var[float | int] | float | int | None = None,
        font_size: Var[float | int] | float | int | None = None,
        draw_duration: Var[float | int] | float | int | None = None,
        fold_duration: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_select: Optional[EventType[Any]] = None,
        on_toggle: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "BranchedMenu":
        """Copy the component source into the app (once) and create the component."""
        ...

class CallChip(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        icon: Component | Var[Component | str] | str | None = None,
        name: Var[str] | str | None = None,
        argument: Var[str] | str | None = None,
        status: Literal["done", "error", "idle", "running"]
        | Var[Literal["done", "error", "idle", "running"]]
        | None = None,
        expected_ms: Var[float | int] | float | int | None = None,
        size: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        color: Var[str] | str | None = None,
        surface_color: Var[str] | str | None = None,
        progress_color: Var[str] | str | None = None,
        progress_opacity: Var[float | int] | float | int | None = None,
        done_color: Var[str] | str | None = None,
        error_color: Var[str] | str | None = None,
        wash_opacity: Var[float | int] | float | int | None = None,
        shake: Var[float | int] | float | int | None = None,
        show_timer: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_retry: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CallChip":
        """Copy the component source into the app (once) and create the component."""
        ...

class CodeSlots(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        length: Var[float | int] | float | int | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        status: Literal["error", "idle", "success"]
        | Var[Literal["error", "idle", "success"]]
        | None = None,
        mask: Var[bool] | bool | None = None,
        caret: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        auto_focus: Var[bool] | bool | None = None,
        accent_color: Var[str] | str | None = None,
        ink_color: Var[str] | str | None = None,
        slot_color: Var[str] | str | None = None,
        digit_color: Var[str] | str | None = None,
        danger_color: Var[str] | str | None = None,
        slot_size: Var[float | int] | float | int | None = None,
        gap: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        bounce: Var[float | int] | float | int | None = None,
        settle: Var[float | int] | float | int | None = None,
        rise: Var[float | int] | float | int | None = None,
        cascade: Var[float | int] | float | int | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_complete: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CodeSlots":
        """Copy the component source into the app (once) and create the component."""
        ...

class CometDial(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[float | int] | float | int | None = None,
        default_value: Var[float | int] | float | int | None = None,
        min: Var[float | int] | float | int | None = None,
        max: Var[float | int] | float | int | None = None,
        step: Var[float | int] | float | int | None = None,
        unit: Var[str] | str | None = None,
        label: Var[str] | str | None = None,
        accent: Var[str] | str | None = None,
        ink: Var[str] | str | None = None,
        size: Var[float | int] | float | int | None = None,
        sweep: Var[float | int] | float | int | None = None,
        thickness: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        tap_bounce: Var[float | int] | float | int | None = None,
        flick_bounce: Var[float | int] | float | int | None = None,
        momentum: Var[float | int] | float | int | None = None,
        comet_reach: Var[float | int] | float | int | None = None,
        comet_width: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_change_end: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CometDial":
        """Copy the component source into the app (once) and create the component."""
        ...

class DodgeField(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        taunts: Var[list[str]] | list[str] | None = None,
        notice: Var[str] | str | None = None,
        ink_color: Var[str] | str | None = None,
        contrast_color: Var[str] | str | None = None,
        field_height: Var[float | int] | float | int | None = None,
        reach: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        falloff: Var[float | int] | float | int | None = None,
        flee_duration: Var[float | int] | float | int | None = None,
        return_duration: Var[float | int] | float | int | None = None,
        return_bounce: Var[float | int] | float | int | None = None,
        axis: Literal["both", "x", "y"] | Var[Literal["both", "x", "y"]] | None = None,
        wall: Literal["bounce", "clamp"] | Var[Literal["bounce", "clamp"]] | None = None,
        patience: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_catch: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_dodge: Optional[EventType[Any]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_relent: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "DodgeField":
        """Copy the component source into the app (once) and create the component."""
        ...

class FolderFloat(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[Any]] | list[Any] | None = None,
        label: Var[str] | str | None = None,
        sublabel: Var[str] | str | None = None,
        trigger: Literal["click", "hover"] | Var[Literal["click", "hover"]] | None = None,
        default_open: Var[bool] | bool | None = None,
        close_on_select: Var[bool] | bool | None = None,
        physics: Var[bool] | bool | None = None,
        drift: Var[float | int] | float | int | None = None,
        folder_color: Var[str] | str | None = None,
        front_color: Var[str] | str | None = None,
        paper_color: Var[str] | str | None = None,
        item_color: Var[str] | str | None = None,
        item_text_color: Var[str] | str | None = None,
        label_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        height: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        spread: Var[float | int] | float | int | None = None,
        lift: Var[float | int] | float | int | None = None,
        tilt: Var[float | int] | float | int | None = None,
        flap_angle: Var[float | int] | float | int | None = None,
        rest_angle: Var[float | int] | float | int | None = None,
        open_duration: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        bounce: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_open_change: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_select: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "FolderFloat":
        """Copy the component source into the app (once) and create the component."""
        ...

class FuseButton(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        undo_label: Var[str] | str | None = None,
        done_label: Var[str] | str | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        color: Var[str] | str | None = None,
        background: Var[str] | str | None = None,
        fuse_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        undo_window: Var[float | int] | float | int | None = None,
        fuse: Literal["bottom", "outline", "top"]
        | Var[Literal["bottom", "outline", "top"]]
        | None = None,
        fuse_thickness: Var[float | int] | float | int | None = None,
        crossfade_ms: Var[float | int] | float | int | None = None,
        commit_on: Literal["fuseEnd", "press"] | Var[Literal["fuseEnd", "press"]] | None = None,
        pause_on_hover: Var[bool] | bool | None = None,
        settle: Literal["reset", "stay"] | Var[Literal["reset", "stay"]] | None = None,
        disabled: Var[bool] | bool | None = None,
        type: Literal["button", "reset", "submit"]
        | Var[Literal["button", "reset", "submit"]]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_commit: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_fuse_end: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_phase_change: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_undo: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "FuseButton":
        """Copy the component source into the app (once) and create the component."""
        ...

class GlideSelect(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        options: Var[list[Any]] | list[Any] | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        placeholder: Var[str] | str | None = None,
        show_tags: Var[bool] | bool | None = None,
        accent_color: Var[str] | str | None = None,
        surface_color: Var[str] | str | None = None,
        highlight_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        menu_width: Var[float | int] | float | int | None = None,
        placement: Literal["bottom", "top"] | Var[Literal["bottom", "top"]] | None = None,
        align: Literal["left", "right"] | Var[Literal["left", "right"]] | None = None,
        pop_duration: Var[float | int] | float | int | None = None,
        glide_duration: Var[float | int] | float | int | None = None,
        remember_position: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "GlideSelect":
        """Copy the component source into the app (once) and create the component."""
        ...

class HoldButton(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        done_label: Component | Var[Component | str] | str | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        done_icon: Component | Var[Component | str] | str | None = None,
        background_color: Var[str] | str | None = None,
        fill_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        fill_text_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        fill_direction: Literal["right", "up"] | Var[Literal["right", "up"]] | None = None,
        hold_time: Var[float | int] | float | int | None = None,
        release_time: Var[float | int] | float | int | None = None,
        press_scale: Var[float | int] | float | int | None = None,
        wave: Var[bool] | bool | None = None,
        wave_amplitude: Var[float | int] | float | int | None = None,
        glow: Var[bool] | bool | None = None,
        reset_after: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_hold: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_tap: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "HoldButton":
        """Copy the component source into the app (once) and create the component."""
        ...

class JellyRadio(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[Any]] | list[Any] | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        chip_color: Var[str] | str | None = None,
        active_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        active_text_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        gap: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        swell: Var[float | int] | float | int | None = None,
        barge: Var[float | int] | float | int | None = None,
        shrink: Var[float | int] | float | int | None = None,
        jelly: Var[float | int] | float | int | None = None,
        bounce: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        stiffness: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "JellyRadio":
        """Copy the component source into the app (once) and create the component."""
        ...

class LatticeLoader(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        done_label: Var[str] | str | None = None,
        error_label: Var[str] | str | None = None,
        status: Literal["done", "error", "working"]
        | Var[Literal["done", "error", "working"]]
        | None = None,
        pattern: Var[dict[str, Any] | str] | dict[str, Any] | str | None = None,
        grid: Var[float | int] | float | int | None = None,
        shape: Literal["round", "square"] | Var[Literal["round", "square"]] | None = None,
        color: Var[str] | str | None = None,
        done_color: Var[str] | str | None = None,
        error_color: Var[str] | str | None = None,
        cell_size: Var[float | int] | float | int | None = None,
        gap: Var[float | int] | float | int | None = None,
        font_size: Var[float | int] | float | int | None = None,
        step: Var[float | int] | float | int | None = None,
        idle_opacity: Var[float | int] | float | int | None = None,
        glow: Var[bool] | bool | None = None,
        glow_color: Var[str] | str | None = None,
        show_timer: Var[bool] | bool | None = None,
        elapsed: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "LatticeLoader":
        """Copy the component source into the app (once) and create the component."""
        ...

class PeekRating(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[float | int] | float | int | None = None,
        default_value: Var[float | int] | float | int | None = None,
        count: Var[float | int] | float | int | None = None,
        shape: Literal["bolt", "heart", "star"]
        | Var[Literal["bolt", "heart", "star"]]
        | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        labels: Var[list[str]] | list[str] | None = None,
        active_color: Var[str] | str | None = None,
        idle_color: Var[str] | str | None = None,
        tip_color: Var[str] | str | None = None,
        tip_text_color: Var[str] | str | None = None,
        size: Var[float | int] | float | int | None = None,
        lift: Var[float | int] | float | int | None = None,
        magnify: Var[float | int] | float | int | None = None,
        rise_duration: Var[float | int] | float | int | None = None,
        pop_scale: Var[float | int] | float | int | None = None,
        show_tip: Var[bool] | bool | None = None,
        allow_clear: Var[bool] | bool | None = None,
        read_only: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_preview: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PeekRating":
        """Copy the component source into the app (once) and create the component."""
        ...

class PromptBar(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        placeholder: Var[str] | str | None = None,
        sources: Var[list[Any]] | list[Any] | None = None,
        commands: Var[list[Any]] | list[Any] | None = None,
        models: Var[list[Any]] | list[Any] | None = None,
        default_model: Var[str] | str | None = None,
        efforts: Var[list[str]] | list[str] | None = None,
        default_effort: Var[str] | str | None = None,
        busy: Var[bool] | bool | None = None,
        background: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        menu_background: Var[str] | str | None = None,
        spark_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        max_rows: Var[float | int] | float | int | None = None,
        morph_duration: Var[float | int] | float | int | None = None,
        squash: Var[float | int] | float | int | None = None,
        tilt: Var[float | int] | float | int | None = None,
        press_scale: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_attach: Optional[EventType[()]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_dictate: Optional[EventType[()]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_effort_change: Optional[EventType[Any]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_send: Optional[EventType[Any]] = None,
        on_stop: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PromptBar":
        """Copy the component source into the app (once) and create the component."""
        ...

class PulseHeart(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        liked: Var[bool] | bool | None = None,
        default_liked: Var[bool] | bool | None = None,
        count: Var[float | int] | float | int | None = None,
        show_count: Var[bool] | bool | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        idle_outline: Var[bool] | bool | None = None,
        size: Var[float | int] | float | int | None = None,
        corner: Var[float | int] | float | int | None = None,
        liked_color: Var[str] | str | None = None,
        idle_color: Var[str] | str | None = None,
        pill_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        duration: Var[float | int] | float | int | None = None,
        dot_size: Var[float | int] | float | int | None = None,
        overshoot: Var[float | int] | float | int | None = None,
        beat: Var[float | int] | float | int | None = None,
        roll_duration: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PulseHeart":
        """Copy the component source into the app (once) and create the component."""
        ...

class RefineFrame(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        status: Literal["complete", "error", "generating", "queued", "refining"]
        | Var[Literal["complete", "error", "generating", "queued", "refining"]]
        | None = None,
        aspect_ratio: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        background: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        stage_duration: Var[float | int] | float | int | None = None,
        sweep: Var[bool] | bool | None = None,
        show_status: Var[bool] | bool | None = None,
        hide_after: Var[float | int] | float | int | None = None,
        labels: Var[dict[str, Any]] | dict[str, Any] | None = None,
        retry_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_retry: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "RefineFrame":
        """Copy the component source into the app (once) and create the component."""
        ...

class RubberSegment(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        items: Var[list[Any]] | list[Any] | None = None,
        value: Var[str] | str | None = None,
        default_value: Var[str] | str | None = None,
        track_color: Var[str] | str | None = None,
        thumb_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        active_text_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        inset: Var[float | int] | float | int | None = None,
        equal_slots: Var[bool] | bool | None = None,
        stretch: Var[float | int] | float | int | None = None,
        squash: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        glide: Var[float | int] | float | int | None = None,
        draggable: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "RubberSegment":
        """Copy the component source into the app (once) and create the component."""
        ...

class ScrubField(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        suffix: Var[str] | str | None = None,
        value: Var[float | int] | float | int | None = None,
        default_value: Var[float | int] | float | int | None = None,
        min: Var[float | int] | float | int | None = None,
        max: Var[float | int] | float | int | None = None,
        step: Var[float | int] | float | int | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        sensitivity: Var[float | int] | float | int | None = None,
        rubber_reach: Var[float | int] | float | int | None = None,
        return_duration: Var[float | int] | float | int | None = None,
        coarse_multiplier: Var[float | int] | float | int | None = None,
        fine_multiplier: Var[float | int] | float | int | None = None,
        show_delta: Var[bool] | bool | None = None,
        show_dirty: Var[bool] | bool | None = None,
        show_fill: Var[bool] | bool | None = None,
        accent: Var[str] | str | None = None,
        chip_color: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_commit: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScrubField":
        """Copy the component source into the app (once) and create the component."""
        ...

class SlideCommit(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Component | Var[Component | str] | str | None = None,
        done_label: Component | Var[Component | str] | str | None = None,
        error_label: Component | Var[Component | str] | str | None = None,
        track_color: Var[str] | str | None = None,
        handle_color: Var[str] | str | None = None,
        success_color: Var[str] | str | None = None,
        danger_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        height: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        return_bounce: Var[float | int] | float | int | None = None,
        landing_dip: Var[float | int] | float | int | None = None,
        hold_ms: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_confirm: Optional[EventType[()]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_done: Optional[EventType[()]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_error: Optional[EventType[Any]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SlideCommit":
        """Copy the component source into the app (once) and create the component."""
        ...

class SlingButton(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        pad_color: Var[str] | str | None = None,
        icon_color: Var[str] | str | None = None,
        accent_color: Var[str] | str | None = None,
        well_color: Var[str] | str | None = None,
        band_color: Var[str] | str | None = None,
        size: Var[float | int] | float | int | None = None,
        stroke_width: Var[float | int] | float | int | None = None,
        arm_at: Var[float | int] | float | int | None = None,
        max_pull: Var[float | int] | float | int | None = None,
        launch_speed: Var[float | int] | float | int | None = None,
        recoil: Var[float | int] | float | int | None = None,
        flight: Var[float | int] | float | int | None = None,
        axis: Literal["any", "horizontal", "vertical"]
        | Var[Literal["any", "horizontal", "vertical"]]
        | None = None,
        tap_sends: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_send: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SlingButton":
        """Copy the component source into the app (once) and create the component."""
        ...

class SloshGauge(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[float | int] | float | int | None = None,
        default_value: Var[float | int] | float | int | None = None,
        interactive: Var[bool] | bool | None = None,
        show_value: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        liquid_color: Var[str] | str | None = None,
        glass_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        height: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        ticks: Var[float | int] | float | int | None = None,
        viscosity: Var[float | int] | float | int | None = None,
        tilt: Var[float | int] | float | int | None = None,
        splash: Var[float | int] | float | int | None = None,
        unit: Var[str] | str | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SloshGauge":
        """Copy the component source into the app (once) and create the component."""
        ...

class SpringCheck(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Component | Var[Component | str] | str | None = None,
        checked: Var[bool] | bool | None = None,
        default_checked: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        color: Var[str] | str | None = None,
        fill_color: Var[str] | str | None = None,
        check_color: Var[str] | str | None = None,
        box_size: Var[float | int] | float | int | None = None,
        box_radius: Var[float | int] | float | int | None = None,
        font_size: Var[float | int] | float | int | None = None,
        bounce: Var[float | int] | float | int | None = None,
        strike_lag: Var[float | int] | float | int | None = None,
        done_opacity: Var[float | int] | float | int | None = None,
        strike: Literal["center", "left", "none", "right"]
        | Var[Literal["center", "left", "none", "right"]]
        | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SpringCheck":
        """Copy the component source into the app (once) and create the component."""
        ...

class SquishSwitch(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        checked: Var[bool] | bool | None = None,
        default_checked: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        track_color: Var[str] | str | None = None,
        track_on_color: Var[str] | str | None = None,
        thumb_color: Var[str] | str | None = None,
        thumb_on_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        height: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        stretch: Var[float | int] | float | int | None = None,
        hover_scale: Var[float | int] | float | int | None = None,
        color_duration: Var[float | int] | float | int | None = None,
        aria_label: Var[str] | str | None = None,
        id_: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SquishSwitch":
        """Copy the component source into the app (once) and create the component."""
        ...

class StatusMark(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        status: Literal["cancelled", "done", "failed", "pending", "running"]
        | Var[Literal["cancelled", "done", "failed", "pending", "running"]]
        | None = None,
        progress: Var[float | int] | float | int | None = None,
        label: Component | Var[Component | str] | str | None = None,
        color: Var[str] | str | None = None,
        done_color: Var[str] | str | None = None,
        error_color: Var[str] | str | None = None,
        size: Var[float | int] | float | int | None = None,
        stroke_width: Var[float | int] | float | int | None = None,
        dashes: Var[float | int] | float | int | None = None,
        font_size: Var[float | int] | float | int | None = None,
        spin_duration: Var[float | int] | float | int | None = None,
        arc_length: Var[float | int] | float | int | None = None,
        draw_duration: Var[float | int] | float | int | None = None,
        fill_opacity: Var[float | int] | float | int | None = None,
        strike: Var[bool] | bool | None = None,
        strike_delay: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "StatusMark":
        """Copy the component source into the app (once) and create the component."""
        ...

class SwipeRow(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        actions: Var[list[Any]] | list[Any] | None = None,
        action_color: Var[str] | str | None = None,
        drawer_color: Var[str] | str | None = None,
        row_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        height: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        action_width: Var[float | int] | float | int | None = None,
        direction: Literal["left", "right"] | Var[Literal["left", "right"]] | None = None,
        snap_bounce: Var[float | int] | float | int | None = None,
        resistance: Var[float | int] | float | int | None = None,
        collapse_ms: Var[float | int] | float | int | None = None,
        commit_at: Var[float | int] | float | int | None = None,
        full_swipe: Var[bool] | bool | None = None,
        disabled: Var[bool] | bool | None = None,
        open: Var[bool] | bool | None = None,
        close_on_action: Var[bool] | bool | None = None,
        haptic: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_action: Optional[EventType[Any]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_commit: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_open_change: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SwipeRow":
        """Copy the component source into the app (once) and create the component."""
        ...

class SwipeToast(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        title: Component | Var[Component | str] | str | None = None,
        description: Component | Var[Component | str] | str | None = None,
        icon: Component | Var[Component | str] | str | None = None,
        action_label: Component | Var[Component | str] | str | None = None,
        open: Var[bool] | bool | None = None,
        background: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        fuse_color: Var[str] | str | None = None,
        width: Var[float | int] | float | int | None = None,
        radius: Var[float | int] | float | int | None = None,
        slide_ms: Var[float | int] | float | int | None = None,
        settle_bounce: Var[float | int] | float | int | None = None,
        swipe_distance: Var[float | int] | float | int | None = None,
        duration: Var[float | int] | float | int | None = None,
        fuse: Literal["bottom", "none", "top"]
        | Var[Literal["bottom", "none", "top"]]
        | None = None,
        pause_on_hover: Var[bool] | bool | None = None,
        close_button: Var[bool] | bool | None = None,
        inline: Var[bool] | bool | None = None,
        dismissible: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_action: Optional[EventType[()]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_close: Optional[EventType[Any]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SwipeToast":
        """Copy the component source into the app (once) and create the component."""
        ...

class ThoughtLine(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        done_label: Var[str] | str | None = None,
        render_label: Any | Var[Any] | None = None,
        glyph: Component | Var[Component | str] | str | None = None,
        steps: Var[list[str]] | list[str] | None = None,
        collapsible: Var[bool] | bool | None = None,
        collapse_on_settle: Var[bool] | bool | None = None,
        color: Var[str] | str | None = None,
        glyph_color: Var[str] | str | None = None,
        font_size: Var[float | int] | float | int | None = None,
        breath_period: Var[float | int] | float | int | None = None,
        breath_depth: Var[float | int] | float | int | None = None,
        shimmer: Var[bool] | bool | None = None,
        shimmer_duration: Var[float | int] | float | int | None = None,
        settle_duration: Var[float | int] | float | int | None = None,
        settle_blur: Var[float | int] | float | int | None = None,
        working: Var[bool] | bool | None = None,
        settle_after: Var[float | int] | float | int | None = None,
        elapsed: Var[float | int] | float | int | None = None,
        show_timer: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_settle: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ThoughtLine":
        """Copy the component source into the app (once) and create the component."""
        ...

class VoicePill(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        accent_color: Var[str] | str | None = None,
        icon_color: Var[str] | str | None = None,
        background: Var[str] | str | None = None,
        size: Var[float | int] | float | int | None = None,
        shape: Literal["pill", "rounded"] | Var[Literal["pill", "rounded"]] | None = None,
        reach: Var[float | int] | float | int | None = None,
        show_time: Var[bool] | bool | None = None,
        waveform: Var[bool] | bool | None = None,
        slide_to_cancel: Var[bool] | bool | None = None,
        cancel_distance: Var[float | int] | float | int | None = None,
        attack: Var[float | int] | float | int | None = None,
        release: Var[float | int] | float | int | None = None,
        sensitivity: Var[float | int] | float | int | None = None,
        floor: Var[float | int] | float | int | None = None,
        open_duration: Var[float | int] | float | int | None = None,
        press_scale: Var[float | int] | float | int | None = None,
        mode: Literal["auto", "hold", "toggle"]
        | Var[Literal["auto", "hold", "toggle"]]
        | None = None,
        hold_after: Var[float | int] | float | int | None = None,
        reactive: Literal["mic", "simulated"] | Var[Literal["mic", "simulated"]] | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_start: Optional[EventType[Any]] = None,
        on_stop: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "VoicePill":
        """Copy the component source into the app (once) and create the component."""
        ...

class WakeSlider(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[float | int] | float | int | None = None,
        default_value: Var[float | int] | float | int | None = None,
        min: Var[float | int] | float | int | None = None,
        max: Var[float | int] | float | int | None = None,
        step: Var[float | int] | float | int | None = None,
        bars: Var[float | int] | float | int | None = None,
        height: Var[float | int] | float | int | None = None,
        rest_height: Var[float | int] | float | int | None = None,
        gap: Var[float | int] | float | int | None = None,
        fill_color: Var[str] | str | None = None,
        track_color: Var[str] | str | None = None,
        crest_color: Var[str] | str | None = None,
        sensitivity: Var[float | int] | float | int | None = None,
        reach: Var[float | int] | float | int | None = None,
        skew: Var[float | int] | float | int | None = None,
        glide: Var[float | int] | float | int | None = None,
        smoothing: Var[float | int] | float | int | None = None,
        show_value: Var[bool] | bool | None = None,
        format_value: Any | Var[Any] | None = None,
        disabled: Var[bool] | bool | None = None,
        aria_label: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[Any]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WakeSlider":
        """Copy the component source into the app (once) and create the component."""
        ...

class WarmTooltip(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        content: Component | Var[Component | str] | str | None = None,
        shortcut: Component | Var[Component | str] | str | None = None,
        side: Literal["bottom", "left", "right", "top"]
        | Var[Literal["bottom", "left", "right", "top"]]
        | None = None,
        delay: Var[float | int] | float | int | None = None,
        warm_window: Var[float | int] | float | int | None = None,
        surface_color: Var[str] | str | None = None,
        ink_color: Var[str] | str | None = None,
        size: Literal["lg", "md", "sm"] | Var[Literal["lg", "md", "sm"]] | None = None,
        radius: Var[float | int] | float | int | None = None,
        gap: Var[float | int] | float | int | None = None,
        arrow: Var[bool] | bool | None = None,
        pop_duration: Var[float | int] | float | int | None = None,
        pop_scale: Var[float | int] | float | int | None = None,
        pop_blur: Var[float | int] | float | int | None = None,
        show_fuse: Var[bool] | bool | None = None,
        long_press: Var[float | int] | float | int | None = None,
        disabled: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WarmTooltip":
        """Copy the component source into the app (once) and create the component."""
        ...

class WarmTooltipGroup(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        delay: Var[float | int] | float | int | None = None,
        warm_window: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WarmTooltipGroup":
        """Copy the component source into the app (once) and create the component."""
        ...

bell_toggle = BellToggle.create
branched_menu = BranchedMenu.create
call_chip = CallChip.create
code_slots = CodeSlots.create
comet_dial = CometDial.create
dodge_field = DodgeField.create
folder_float = FolderFloat.create
fuse_button = FuseButton.create
glide_select = GlideSelect.create
hold_button = HoldButton.create
jelly_radio = JellyRadio.create
lattice_loader = LatticeLoader.create
peek_rating = PeekRating.create
prompt_bar = PromptBar.create
pulse_heart = PulseHeart.create
refine_frame = RefineFrame.create
rubber_segment = RubberSegment.create
scrub_field = ScrubField.create
slide_commit = SlideCommit.create
sling_button = SlingButton.create
slosh_gauge = SloshGauge.create
spring_check = SpringCheck.create
squish_switch = SquishSwitch.create
status_mark = StatusMark.create
swipe_row = SwipeRow.create
swipe_toast = SwipeToast.create
thought_line = ThoughtLine.create
voice_pill = VoicePill.create
wake_slider = WakeSlider.create
warm_tooltip = WarmTooltip.create
warm_tooltip_group = WarmTooltipGroup.create
