"""Stub file for reflex_reactbits/text_animations.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.components.component import Component
from reflex_base.vars.base import Var
from .base import ReactBitsComponent

__all__ = [
    "ASCIIText",
    "BlurText",
    "CircularText",
    "CountUp",
    "CurvedLoop",
    "DecryptedText",
    "DepthText",
    "EchoText",
    "FallingText",
    "FoldText",
    "FuzzyText",
    "GlitchText",
    "GradientText",
    "MaskedHeading",
    "ParticleText",
    "RotatingText",
    "ScrambledText",
    "ScrollFloat",
    "ScrollReveal",
    "ScrollVelocity",
    "ShinyText",
    "Shuffle",
    "SplitFlapText",
    "SplitText",
    "StrokeText",
    "TextCursor",
    "TextLoop",
    "TextPressure",
    "TextType",
    "TrueFocus",
    "VariableProximity",
    "WarpText",
    "ascii_text",
    "blur_text",
    "circular_text",
    "count_up",
    "curved_loop",
    "decrypted_text",
    "depth_text",
    "echo_text",
    "falling_text",
    "fold_text",
    "fuzzy_text",
    "glitch_text",
    "gradient_text",
    "masked_heading",
    "particle_text",
    "rotating_text",
    "scrambled_text",
    "scroll_float",
    "scroll_reveal",
    "scroll_velocity",
    "shiny_text",
    "shuffle",
    "split_flap_text",
    "split_text",
    "stroke_text",
    "text_cursor",
    "text_loop",
    "text_pressure",
    "text_type",
    "true_focus",
    "variable_proximity",
    "warp_text",
]

class ASCIIText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        ascii_font_size: Var[float | int] | float | int | None = None,
        text_font_size: Var[float | int] | float | int | None = None,
        text_color: Var[str] | str | None = None,
        plane_base_height: Var[float | int] | float | int | None = None,
        enable_waves: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ASCIIText":
        """Copy the component source into the app (once) and create the component."""
        ...

class BlurText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        delay: Var[float | int] | float | int | None = None,
        animate_by: Var[str] | str | None = None,
        direction: Var[str] | str | None = None,
        threshold: Var[float | int] | float | int | None = None,
        root_margin: Var[str] | str | None = None,
        animation_from: Any | Var[Any] | None = None,
        animation_to: Any | Var[Any] | None = None,
        easing: Any | Var[Any] | None = None,
        step_duration: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_animation_complete: Optional[EventType[()]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "BlurText":
        """Copy the component source into the app (once) and create the component."""
        ...

class CircularText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        spin_duration: Var[float | int] | float | int | None = None,
        on_hover: Literal["goBonkers", "pause", "slowDown", "speedUp"]
        | Var[Literal["goBonkers", "pause", "slowDown", "speedUp"]]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CircularText":
        """Copy the component source into the app (once) and create the component."""
        ...

class CountUp(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        to: Var[float | int] | float | int | None = None,
        from_: Var[float | int] | float | int | None = None,
        direction: Var[str] | str | None = None,
        delay: Var[float | int] | float | int | None = None,
        duration: Var[float | int] | float | int | None = None,
        start_when: Var[bool] | bool | None = None,
        separator: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_end: Optional[EventType[()]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_start: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CountUp":
        """Copy the component source into the app (once) and create the component."""
        ...

class CurvedLoop(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        marquee_text: Var[str] | str | None = None,
        speed: Var[float | int] | float | int | None = None,
        curve_amount: Var[float | int] | float | int | None = None,
        direction: Literal["left", "right"] | Var[Literal["left", "right"]] | None = None,
        interactive: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "CurvedLoop":
        """Copy the component source into the app (once) and create the component."""
        ...

class DecryptedText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        speed: Var[float | int] | float | int | None = None,
        max_iterations: Var[float | int] | float | int | None = None,
        sequential: Var[bool] | bool | None = None,
        reveal_direction: Literal["center", "end", "start"]
        | Var[Literal["center", "end", "start"]]
        | None = None,
        use_original_chars_only: Var[bool] | bool | None = None,
        characters: Var[str] | str | None = None,
        parent_class_name: Var[str] | str | None = None,
        encrypted_class_name: Var[str] | str | None = None,
        animate_on: Literal["click", "hover", "inViewHover", "view"]
        | Var[Literal["click", "hover", "inViewHover", "view"]]
        | None = None,
        click_mode: Literal["once", "toggle"] | Var[Literal["once", "toggle"]] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "DecryptedText":
        """Copy the component source into the app (once) and create the component."""
        ...

class DepthText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        layers: Var[float | int] | float | int | None = None,
        depth: Var[float | int] | float | int | None = None,
        face_color: Var[str] | str | None = None,
        depth_color: Var[str] | str | None = None,
        tilt: Var[float | int] | float | int | None = None,
        pointer_tracking: Var[bool] | bool | None = None,
        smoothing: Var[float | int] | float | int | None = None,
        perspective: Var[float | int] | float | int | None = None,
        auto_orbit: Var[bool] | bool | None = None,
        orbit_speed: Var[float | int] | float | int | None = None,
        font_size: Var[str] | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        shadow: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "DepthText":
        """Copy the component source into the app (once) and create the component."""
        ...

class EchoText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        echoes: Var[float | int] | float | int | None = None,
        lag: Var[float | int] | float | int | None = None,
        offset: Var[float | int] | float | int | None = None,
        direction: Literal["diagonal", "down", "left", "right", "up"]
        | Var[Literal["diagonal", "down", "left", "right", "up"]]
        | None = None,
        fade: Var[float | int] | float | int | None = None,
        blur: Var[float | int] | float | int | None = None,
        tint: Var[bool | str] | bool | str | None = None,
        mode: Literal["both", "entrance", "pointer"]
        | Var[Literal["both", "entrance", "pointer"]]
        | None = None,
        cursor_radius: Var[float | int] | float | int | None = None,
        duration: Var[float | int] | float | int | None = None,
        ease: Literal["ease-in-out", "ease-out", "linear", "snappy"]
        | Var[Literal["ease-in-out", "ease-out", "linear", "snappy"]]
        | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        color: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "EchoText":
        """Copy the component source into the app (once) and create the component."""
        ...

class FallingText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        highlight_words: Var[list[str]] | list[str] | None = None,
        highlight_class: Var[str] | str | None = None,
        trigger: Literal["auto", "click", "hover", "scroll"]
        | Var[Literal["auto", "click", "hover", "scroll"]]
        | None = None,
        background_color: Var[str] | str | None = None,
        wireframes: Var[bool] | bool | None = None,
        gravity: Var[float | int] | float | int | None = None,
        mouse_constraint_stiffness: Var[float | int] | float | int | None = None,
        font_size: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "FallingText":
        """Copy the component source into the app (once) and create the component."""
        ...

class FoldText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        split_by: Literal["char", "line", "word"]
        | Var[Literal["char", "line", "word"]]
        | None = None,
        hinge: Literal["bottom", "left", "right", "top"]
        | Var[Literal["bottom", "left", "right", "top"]]
        | None = None,
        duration: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        ease: Var[str] | str | None = None,
        perspective: Var[float | int] | float | int | None = None,
        crease_shading: Var[float | int] | float | int | None = None,
        trigger: Literal["hover", "loop", "mount", "scroll"]
        | Var[Literal["hover", "loop", "mount", "scroll"]]
        | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        color: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "FoldText":
        """Copy the component source into the app (once) and create the component."""
        ...

class FuzzyText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        font_family: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        enable_hover: Var[bool] | bool | None = None,
        base_intensity: Var[float | int] | float | int | None = None,
        hover_intensity: Var[float | int] | float | int | None = None,
        fuzz_range: Var[float | int] | float | int | None = None,
        fps: Var[float | int] | float | int | None = None,
        direction: Literal["both", "horizontal", "vertical"]
        | Var[Literal["both", "horizontal", "vertical"]]
        | None = None,
        transition_duration: Var[float | int] | float | int | None = None,
        click_effect: Var[bool] | bool | None = None,
        glitch_mode: Var[bool] | bool | None = None,
        glitch_interval: Var[float | int] | float | int | None = None,
        glitch_duration: Var[float | int] | float | int | None = None,
        gradient: Var[list[str]] | list[str] | None = None,
        letter_spacing: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "FuzzyText":
        """Copy the component source into the app (once) and create the component."""
        ...

class GlitchText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        speed: Var[float | int] | float | int | None = None,
        enable_shadows: Var[bool] | bool | None = None,
        enable_on_hover: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "GlitchText":
        """Copy the component source into the app (once) and create the component."""
        ...

class GradientText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        colors: Var[list[str]] | list[str] | None = None,
        animation_speed: Var[float | int] | float | int | None = None,
        show_border: Var[bool] | bool | None = None,
        direction: Literal["diagonal", "horizontal", "vertical"]
        | Var[Literal["diagonal", "horizontal", "vertical"]]
        | None = None,
        pause_on_hover: Var[bool] | bool | None = None,
        yoyo: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "GradientText":
        """Copy the component source into the app (once) and create the component."""
        ...

class MaskedHeading(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        tag_: Var[str] | str | None = None,
        media_type: Literal["image", "video"] | Var[Literal["image", "video"]] | None = None,
        src: Var[str] | str | None = None,
        poster: Var[str] | str | None = None,
        fill_scale: Var[float | int] | float | int | None = None,
        parallax: Var[float | int] | float | int | None = None,
        drift: Var[float | int] | float | int | None = None,
        brightness: Var[float | int] | float | int | None = None,
        saturation: Var[float | int] | float | int | None = None,
        grayscale: Var[bool] | bool | None = None,
        reveal: Literal["fade", "none", "rise", "wipe"]
        | Var[Literal["fade", "none", "rise", "wipe"]]
        | None = None,
        duration: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        trigger: Literal["hover", "mount", "view"]
        | Var[Literal["hover", "mount", "view"]]
        | None = None,
        align: Literal["center", "left", "right"]
        | Var[Literal["center", "left", "right"]]
        | None = None,
        weight: Var[float | int] | float | int | None = None,
        tracking: Var[float | int] | float | int | None = None,
        line_height: Var[float | int] | float | int | None = None,
        text_scale: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "MaskedHeading":
        """Copy the component source into the app (once) and create the component."""
        ...

class ParticleText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        particle_size: Var[float | int] | float | int | None = None,
        density: Var[float | int] | float | int | None = None,
        color: Var[str] | str | None = None,
        highlight_color: Var[str] | str | None = None,
        scatter: Var[float | int] | float | int | None = None,
        gather_duration: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        pointer_repel: Var[float | int] | float | int | None = None,
        repel_radius: Var[float | int] | float | int | None = None,
        idle_drift: Var[float | int] | float | int | None = None,
        trigger: Literal["click", "hover", "mount"]
        | Var[Literal["click", "hover", "mount"]]
        | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        font_family: Var[str] | str | None = None,
        glow: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ParticleText":
        """Copy the component source into the app (once) and create the component."""
        ...

class RotatingText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        texts: Var[list[str]] | list[str] | None = None,
        transition: Var[dict[str, Any]] | dict[str, Any] | None = None,
        initial: Var[dict[str, Any]] | dict[str, Any] | None = None,
        animate: Var[dict[str, Any]] | dict[str, Any] | None = None,
        exit: Var[dict[str, Any]] | dict[str, Any] | None = None,
        animate_presence_mode: Var[str] | str | None = None,
        animate_presence_initial: Var[bool] | bool | None = None,
        rotation_interval: Var[float | int] | float | int | None = None,
        stagger_duration: Var[float | int] | float | int | None = None,
        stagger_from: Var[str] | str | None = None,
        loop: Var[bool] | bool | None = None,
        auto: Var[bool] | bool | None = None,
        split_by: Var[str] | str | None = None,
        main_class_name: Var[str] | str | None = None,
        split_level_class_name: Var[str] | str | None = None,
        element_level_class_name: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_next: Optional[EventType[Any]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "RotatingText":
        """Copy the component source into the app (once) and create the component."""
        ...

class ScrambledText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        radius: Var[float | int] | float | int | None = None,
        duration: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        scramble_chars: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScrambledText":
        """Copy the component source into the app (once) and create the component."""
        ...

class ScrollFloat(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        scroll_container_ref: Any | Var[Any] | None = None,
        container_class_name: Var[str] | str | None = None,
        text_class_name: Var[str] | str | None = None,
        animation_duration: Var[float | int] | float | int | None = None,
        ease: Var[str] | str | None = None,
        scroll_start: Var[str] | str | None = None,
        scroll_end: Var[str] | str | None = None,
        stagger: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScrollFloat":
        """Copy the component source into the app (once) and create the component."""
        ...

class ScrollReveal(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        scroll_container_ref: Any | Var[Any] | None = None,
        enable_blur: Var[bool] | bool | None = None,
        base_opacity: Var[float | int] | float | int | None = None,
        base_rotation: Var[float | int] | float | int | None = None,
        blur_strength: Var[float | int] | float | int | None = None,
        container_class_name: Var[str] | str | None = None,
        text_class_name: Var[str] | str | None = None,
        rotation_end: Var[str] | str | None = None,
        word_animation_end: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScrollReveal":
        """Copy the component source into the app (once) and create the component."""
        ...

class ScrollVelocity(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        scroll_container_ref: Any | Var[Any] | None = None,
        texts: Var[list[Any]] | list[Any] | None = None,
        velocity: Var[float | int] | float | int | None = None,
        damping: Var[float | int] | float | int | None = None,
        stiffness: Var[float | int] | float | int | None = None,
        num_copies: Var[float | int] | float | int | None = None,
        velocity_mapping: Var[list[Any]] | list[Any] | None = None,
        parallax_class_name: Var[str] | str | None = None,
        scroller_class_name: Var[str] | str | None = None,
        parallax_style: Var[dict[str, Any]] | dict[str, Any] | None = None,
        scroller_style: Var[dict[str, Any]] | dict[str, Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScrollVelocity":
        """Copy the component source into the app (once) and create the component."""
        ...

class ShinyText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        speed: Var[float | int] | float | int | None = None,
        color: Var[str] | str | None = None,
        shine_color: Var[str] | str | None = None,
        spread: Var[float | int] | float | int | None = None,
        yoyo: Var[bool] | bool | None = None,
        pause_on_hover: Var[bool] | bool | None = None,
        direction: Literal["left", "right"] | Var[Literal["left", "right"]] | None = None,
        delay: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ShinyText":
        """Copy the component source into the app (once) and create the component."""
        ...

class Shuffle(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        shuffle_direction: Literal["down", "left", "right", "up"]
        | Var[Literal["down", "left", "right", "up"]]
        | None = None,
        duration: Var[float | int] | float | int | None = None,
        max_delay: Var[float | int] | float | int | None = None,
        ease: Any | Var[Any] | None = None,
        threshold: Var[float | int] | float | int | None = None,
        root_margin: Var[str] | str | None = None,
        tag_: Literal["h1", "h2", "h3", "h4", "h5", "h6", "p", "span"]
        | Var[Literal["h1", "h2", "h3", "h4", "h5", "h6", "p", "span"]]
        | None = None,
        text_align: Var[str] | str | None = None,
        shuffle_times: Var[float | int] | float | int | None = None,
        animation_mode: Literal["evenodd", "random"]
        | Var[Literal["evenodd", "random"]]
        | None = None,
        loop: Var[bool] | bool | None = None,
        loop_delay: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        scramble_charset: Var[str] | str | None = None,
        color_from: Var[str] | str | None = None,
        color_to: Var[str] | str | None = None,
        trigger_once: Var[bool] | bool | None = None,
        respect_reduced_motion: Var[bool] | bool | None = None,
        trigger_on_hover: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_shuffle_complete: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "Shuffle":
        """Copy the component source into the app (once) and create the component."""
        ...

class SplitFlapText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        words: Var[list[str]] | list[str] | None = None,
        text: Var[str] | str | None = None,
        flip_duration: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        cycle_delay: Var[float | int] | float | int | None = None,
        charset: Var[str] | str | None = None,
        flips_per_char: Var[float | int] | float | int | None = None,
        tile_color: Var[str] | str | None = None,
        text_color: Var[str] | str | None = None,
        tile_radius: Var[float | int | str] | float | int | str | None = None,
        gap: Var[float | int | str] | float | int | str | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        loop: Var[bool] | bool | None = None,
        pad_to: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SplitFlapText":
        """Copy the component source into the app (once) and create the component."""
        ...

class SplitText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        delay: Var[float | int] | float | int | None = None,
        duration: Var[float | int] | float | int | None = None,
        ease: Var[str] | str | None = None,
        split_type: Var[str] | str | None = None,
        from_: Var[dict[str, Any]] | dict[str, Any] | None = None,
        to: Var[dict[str, Any]] | dict[str, Any] | None = None,
        threshold: Var[float | int] | float | int | None = None,
        root_margin: Var[str] | str | None = None,
        text_align: Var[str] | str | None = None,
        tag_: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_letter_animation_complete: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "SplitText":
        """Copy the component source into the app (once) and create the component."""
        ...

class StrokeText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        stroke_color: Var[str] | str | None = None,
        fill_color: Var[str] | str | None = None,
        stroke_width: Var[float | int] | float | int | None = None,
        draw_duration: Var[float | int] | float | int | None = None,
        fill_delay: Var[float | int] | float | int | None = None,
        stagger: Var[float | int] | float | int | None = None,
        ease: Var[str] | str | None = None,
        trigger: Literal["hover", "loop", "mount", "scroll"]
        | Var[Literal["hover", "loop", "mount", "scroll"]]
        | None = None,
        fill_mode: Literal["fade", "none", "wipe"]
        | Var[Literal["fade", "none", "wipe"]]
        | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        letter_spacing: Var[float | int | str] | float | int | str | None = None,
        reverse: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "StrokeText":
        """Copy the component source into the app (once) and create the component."""
        ...

class TextCursor(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        spacing: Var[float | int] | float | int | None = None,
        follow_mouse_direction: Var[bool] | bool | None = None,
        random_float: Var[bool] | bool | None = None,
        exit_duration: Var[float | int] | float | int | None = None,
        removal_interval: Var[float | int] | float | int | None = None,
        max_points: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TextCursor":
        """Copy the component source into the app (once) and create the component."""
        ...

class TextLoop(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        shape: Literal["arch", "circle", "infinity", "line", "wave"]
        | Var[Literal["arch", "circle", "infinity", "line", "wave"]]
        | None = None,
        path: Var[str] | str | None = None,
        speed: Var[float | int] | float | int | None = None,
        direction: Literal["forward", "reverse"] | Var[Literal["forward", "reverse"]] | None = None,
        separator: Var[str] | str | None = None,
        curviness: Var[float | int] | float | int | None = None,
        font_size: Var[float | int] | float | int | None = None,
        font_weight: Var[float | int] | float | int | None = None,
        letter_spacing: Var[float | int] | float | int | None = None,
        uppercase: Var[bool] | bool | None = None,
        color: Var[str] | str | None = None,
        ribbon: Var[bool] | bool | None = None,
        ribbon_color: Var[str] | str | None = None,
        ribbon_width: Var[float | int] | float | int | None = None,
        pause_on_hover: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TextLoop":
        """Copy the component source into the app (once) and create the component."""
        ...

class TextPressure(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        font_family: Var[str] | str | None = None,
        font_url: Var[str] | str | None = None,
        width: Var[bool] | bool | None = None,
        weight: Var[bool] | bool | None = None,
        italic: Var[bool] | bool | None = None,
        alpha: Var[bool] | bool | None = None,
        flex: Var[bool] | bool | None = None,
        stroke: Var[bool] | bool | None = None,
        scale: Var[bool] | bool | None = None,
        text_color: Var[str] | str | None = None,
        stroke_color: Var[str] | str | None = None,
        min_font_size: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TextPressure":
        """Copy the component source into the app (once) and create the component."""
        ...

class TextType(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[list[str] | str] | list[str] | str | None = None,
        as_: Component | Var[Component | str] | str | None = None,
        typing_speed: Var[float | int] | float | int | None = None,
        initial_delay: Var[float | int] | float | int | None = None,
        pause_duration: Var[float | int] | float | int | None = None,
        deleting_speed: Var[float | int] | float | int | None = None,
        loop: Var[bool] | bool | None = None,
        show_cursor: Var[bool] | bool | None = None,
        hide_cursor_while_typing: Var[bool] | bool | None = None,
        cursor_character: Component | Var[Component | str] | str | None = None,
        cursor_class_name: Var[str] | str | None = None,
        cursor_blink_duration: Var[float | int] | float | int | None = None,
        text_colors: Var[list[str]] | list[str] | None = None,
        variable_speed: Var[dict[str, Any]] | dict[str, Any] | None = None,
        start_on_visible: Var[bool] | bool | None = None,
        reverse_mode: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_sentence_complete: Optional[EventType[Any]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TextType":
        """Copy the component source into the app (once) and create the component."""
        ...

class TrueFocus(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        sentence: Var[str] | str | None = None,
        separator: Var[str] | str | None = None,
        manual_mode: Var[bool] | bool | None = None,
        blur_amount: Var[float | int] | float | int | None = None,
        border_color: Var[str] | str | None = None,
        glow_color: Var[str] | str | None = None,
        animation_duration: Var[float | int] | float | int | None = None,
        pause_between_animations: Var[float | int] | float | int | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "TrueFocus":
        """Copy the component source into the app (once) and create the component."""
        ...

class VariableProximity(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        label: Var[str] | str | None = None,
        from_font_variation_settings: Var[str] | str | None = None,
        to_font_variation_settings: Var[str] | str | None = None,
        container_ref: Any | Var[Any] | None = None,
        radius: Var[float | int] | float | int | None = None,
        falloff: Literal["exponential", "gaussian", "linear"]
        | Var[Literal["exponential", "gaussian", "linear"]]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "VariableProximity":
        """Copy the component source into the app (once) and create the component."""
        ...

class WarpText(ReactBitsComponent):
    @classmethod
    def create(
        cls,
        *children,
        text: Var[str] | str | None = None,
        color: Var[str] | str | None = None,
        warp_strength: Var[float | int] | float | int | None = None,
        warp_scale: Var[float | int] | float | int | None = None,
        speed: Var[float | int] | float | int | None = None,
        pointer_influence: Var[float | int] | float | int | None = None,
        pointer_strength: Var[float | int] | float | int | None = None,
        refraction: Var[float | int] | float | int | None = None,
        ripple: Var[bool] | bool | None = None,
        font_size: Var[float | int | str] | float | int | str | None = None,
        font_weight: Var[float | int | str] | float | int | str | None = None,
        font_family: Var[str] | str | None = None,
        letter_spacing: Var[float | int | str] | float | int | str | None = None,
        line_height: Var[float | int | str] | float | int | str | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "WarpText":
        """Copy the component source into the app (once) and create the component."""
        ...

ascii_text = ASCIIText.create
blur_text = BlurText.create
circular_text = CircularText.create
count_up = CountUp.create
curved_loop = CurvedLoop.create
decrypted_text = DecryptedText.create
depth_text = DepthText.create
echo_text = EchoText.create
falling_text = FallingText.create
fold_text = FoldText.create
fuzzy_text = FuzzyText.create
glitch_text = GlitchText.create
gradient_text = GradientText.create
masked_heading = MaskedHeading.create
particle_text = ParticleText.create
rotating_text = RotatingText.create
scrambled_text = ScrambledText.create
scroll_float = ScrollFloat.create
scroll_reveal = ScrollReveal.create
scroll_velocity = ScrollVelocity.create
shiny_text = ShinyText.create
shuffle = Shuffle.create
split_flap_text = SplitFlapText.create
split_text = SplitText.create
stroke_text = StrokeText.create
text_cursor = TextCursor.create
text_loop = TextLoop.create
text_pressure = TextPressure.create
text_type = TextType.create
true_focus = TrueFocus.create
variable_proximity = VariableProximity.create
warp_text = WarpText.create
